### ISSUE TITLE
Discrepancies on 'Glyph advanceWidth bits length' in 'head' table and value in 'glyf' table

### ISSUE THREAD

**Issue by robekras** [lvgl/lv_font_conv#46] opened 2020-08-18 13:18 UTC
My first tryings with the binary format were with UniFont.
It's a monospaced font.
`lv_font_conv --font unifont-13.0.03.ttf -r 0x020-0x03F --size 12 --no-compress --format bin --bpp 1 -o ./bin/font_20-3f.bin`

As this is a monospaced font, according the source in table_heads.js (line 84-85) a value of 0 is issued for Glyph advanceWidth bits length.
Although within the program the variable f.advanceWidthBits is set to 4 (debug output shows it).
In table 'glyf' the 'glyph data' starts with four bits for the advanceWidth value (four bits are always 0x6). The other values BBox X, etc. (according the specification) are alright and match the values which are issued within the lvgl C-format ().

On the other hand, the value for glyph_dsc[].adv_w within the lvgl C-format shows a 96 (0x60) on every entry (except for special entry 0 of course).

**Comment by puzrin** [comment] 2020-08-19 12:02
Do you use published version or one from master?

Looks dupe of #43, but it was not released yet.

**Comment by robekras** [comment] 2020-08-19 13:38
I installed it with `npm i littlevgl/lv_font_conv -g` about two weeks ago.

**Comment by puzrin** [comment] 2020-08-19 15:04
https://github.com/lvgl/lv_font_conv/commit/b1749edb2540ad9db46b5fd8c242b81a37f0d58e

Please install latest (remove current first) or check if this patch exists.

> What is about the other discrepancy, between the four bit value 0x6 in binary format and the value of 96 (0x60) in glyph_dsc[].adv_w within the lvgl C-format.
> 
> Is it a different meaning between the value in binary format and the one in C-format?

There should not be difference in final value. But lvgl format is based on static structs and is less flexible (it can not skip .adv_w for monospace fonts, for example).

https://github.com/lvgl/lv_font_conv/tree/master/lib/writers/lvgl - here is "extenion" for lvgl writer. If you see more error - just create one more issue.

**Comment by robekras** [comment] 2020-08-20 05:31
Ok, found the reason why the values of advanceWidth between binary and C-format doesn't match.

In lv_table_glyf.js (creation of the C-format) you always do this:
`adv_w = Math.round(d.glyph.advanceWidth * 16)`

and in table_glyf.js you do:
`let w = f.widthToInt(glyph.advanceWidth);`

and as advanceWidthFormat is 0 _widthToInt_ returns a rounded integer (without the *16).
` if (this.advanceWidthFormat === 0) return Math.round(val);`

**Comment by puzrin** [comment] 2020-08-20 11:09
@robekras it's a bit difficult to understand, are you reporting a bug, or share info :). And can this issue be closed as solved (in maser branch) or not.

It may sound strange, but i don't keep deails about project in my head. See how many repos do i have in orgs. The only way to keep mental health is to forget everything after job done :). Opposite to "remember everything" when you have only couple of projects.

Could you say explicit, does latest code from maser needs fix of bin format or not, as reported in initial post? If not - i'd prefer this issue to be closed. If lvgl writer also has problems - it's beter to open new one, because data structures and writers are completely different.

**Comment by robekras** [comment] 2020-08-20 15:34
Sorry for any confusion,

I don't know what the variable advanceWidth is good for, but there is definitly a difference between the value what is issued on C-format, because the original value is always multiplied with 16, and on the other hand, in binary format, it depends on the setting of _this.advanceWidthFormat_. You either take the original value and round it to an integer, that's what I see in binary format (for proportional fonts), or you do a multiply with 16, if _this.advanceWidthFormat_ is != 0.

With Noto font I have a 47 in C-format whereas in binary I have a 3. The original value seems to be something like 47 / 16 = 2.9375.

Of course I can take the 3 multiply it with 16, and get a 48. Which is not the same as 47 in C-format.

I do not know why in C-format advanceWidth is always multiplied with 16, whereas in binary format it could be a rounded integer or multiplied by 16. Also I do not know where the decision is made to set _this.advanceWidthFormat_

I think it means close the issue.

**Comment by puzrin** [comment] 2020-08-20 17:17
Please, can you postpone any kinds of posting about C-format and return to initial issue, about binary format only https://github.com/lvgl/lv_font_conv/issues/46#issue-681035032? You still not confirmed state of that problem. Is it solved in master or not?

**Comment by robekras** [comment] 2020-08-21 05:31
I can confirm, that for monospaced fonts the value for 'Glyph advanceWidth bits length' in head is set to 0, and also that no more bits for advanceWidth is set in glyf data.

**Comment by puzrin** [comment] 2020-08-21 06:06
thanks.

**Closed by puzrin** 2020-08-21 06:06 UTC

**Comment by puzrin** [comment] 2020-08-21 06:37
Returning to your question about `this.advanceWidthFormat` and C output. `--format lvgl` supports ONLY FP12.4 values for width (12 bits int, 4 bits frac). While binary format supports more options.

In short - high precision of glyph width required for kerning, especially when subpixel precision available. But, i your font is monospace - width is integer, and binary format can store value wihou fracional part (i don't remember details how it decides).

I would not recommend to use `--format lvgl` for spec learning, too many undocumented losses.
