### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Pzhaowei** [lvgl/lv_font_conv#68] opened 2022-01-10 11:31 UTC
lv_font_conv --font OPPOSans_OS_Medium_1.4.ttf -r 0x20-0x2c63 --size 32 --format bin --bpp 4 --no-compress -o sans32.font
RangeError: Maximum call stack size exceeded

can you increase the maximum call stack size?

**Comment by puzrin** [comment] 2022-01-10 11:43
Please attach everything required to reproduce (font)

**Comment by Pzhaowei** [comment] 2022-01-11 02:23
[OPPOSans_OS_Medium_1.4.zip](https://github.com/lvgl/lv_font_conv/files/7843157/OPPOSans_OS_Medium_1.4.zip)
This font is free and commercially available

**Comment by Pzhaowei** [comment] 2022-01-11 05:50
> Please attach everything required to reproduce (font). Also, info about font source.

[OPPOSans_OS_Medium.zip](https://github.com/lvgl/lv_font_conv/files/7844012/OPPOSans_OS_Medium.zip)
This font is free and commercially available

**Comment by Pzhaowei** [comment] 2022-01-11 05:58
lv_font_conv --font OPPOSans_OS_Medium.ttf -r 0x20-0xffff --size 24 --format bin --bpp 4 --no-compress -o sans32.font
Error: error in FT_Load_Glyph: -1
at Object.module.exports.glyph_render (C:\Users\11704\AppData\Roaming\npm\node_modules\lv_font_conv\lib\freetype\index.js:205:20)
at collect_font_data (C:\Users\11704\AppData\Roaming\npm\node_modules\lv_font_conv\lib\collect_font_data.js:100:31)
at async convert (C:\Users\11704\AppData\Roaming\npm\node_modules\lv_font_conv\lib\convert.js:24:19)
at async Object.module.exports.run (C:\Users\11704\AppData\Roaming\npm\node_modules\lv_font_conv\lib\cli.js:300:15)

**Comment by puzrin** [comment] 2022-01-11 06:40
Can not reproduce. Cloned repo and executed this:

```sh
./lv_font_conv.js --font OPPOSans_OS_Medium.ttf -r 0x20-0x2c63 --size 32 --format bin --bpp 4 --no-compress -o sans32.font
```

Please, make sure you use latest LTS node.js (v16) and latest convertor version.

**Comment by Pzhaowei** [comment] 2022-01-11 07:15
sorry，please see the problem at #69

**Comment by puzrin** [comment] 2022-01-11 07:16
ref: https://github.com/lvgl/lv_font_conv/issues/69

Regression since node v16.13.1. v16.13.0 works (temporary workaround)

**Comment by puzrin** [comment] 2022-01-11 07:26
Closing in favor of https://github.com/lvgl/lv_font_conv/issues/70

**Closed by puzrin** 2022-01-11 07:26 UTC
