### ISSUE TITLE
this.src.glyphs.map(...).flat is not a function

### ISSUE THREAD

**Issue by marmur99** [lvgl/lv_font_conv#84] opened 2022-11-03 23:44 UTC
Running command:
`lv_font_conv --font AmazonEmber.ttf -r 32-122 --format lvgl --size 40 --bpp 1 -o AmazonEmber40px_zip.c`

error reported:
```
TypeError: this.src.glyphs.map(...).flat is not a function
    at new Font (/usr/local/lib/node_modules/lv_font_conv/lib/font/font.js:38:99)
    at new LvFont (/usr/local/lib/node_modules/lv_font_conv/lib/writers/lvgl/lv_font.js:16:5)
    at Object.write_images [as lvgl] (/usr/local/lib/node_modules/lv_font_conv/lib/writers/lvgl/index.js:12:16)
    at convert (/usr/local/lib/node_modules/lv_font_conv/lib/convert.js:25:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

I downloaded the code as a zip file on 11/3/2022

**Comment by embeddedt** [comment] 2022-11-04 01:14
Duplicate of #73. You will need to update Node.js.

**Closed by embeddedt** 2022-11-04 01:14 UTC
